FoodForYou/Web/FoodForYou.Web/Controllers/CategoriesController.cs
namespace FoodForYou.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using FoodForYou.Common;
    using FoodForYou.Data.Models;
    using FoodForYou.Services.Data.Interfaces;
    using FoodForYou.Services.Interfaces;
    using FoodForYou.Services.Mapping;
    using FoodForYou.Web.ViewModels.Categories;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : BaseController
    {
        private readonly ICategoryService categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        [AllowAnonymous]
        public IActionResult All()
        {
            var categoriesViewModel = new AllCategoriesViewModel
            {
                Categories
                           = this.categoryService.GetAll<CategoriesViewModel>(),
            };

            return this.View(categoriesViewModel);
        }
    }
}

FoodForYou/Web/FoodForYou.Web/Controllers/ContactsController.cs
namespace FoodForYou.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using FoodForYou.Common;
    using FoodForYou.Data.Common.Repositories;
    using FoodForYou.Data.Models;
    using FoodForYou.Services.Messaging;
    using FoodForYou.Web.ViewModels.Contacts;
    using Microsoft.AspNetCore.Mvc;

    public class ContactsController : BaseController
    {
        private readonly IRepository<ContactFormEntry> contactsRepository;

        private readonly IEmailSender emailSender;

        public ContactsController(IRepository<ContactFormEntry> contactsRepository, IEmailSender emailSender)
        {
            this.contactsRepository = contactsRepository;
            this.emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            // TODO: Extract to IP provider (service)
            var ip = this.HttpContext.Connection.RemoteIpAddress.ToString();
            var contactFormEntry = new ContactFormEntry
            {
                Name = model.Name,
                Email = model.Email,
                Title = model.Title,
                Content = model.Content,
                Ip = ip,
            };
            await this.contactsRepository.AddAsync(contactFormEntry);
            await this.contactsRepository.SaveChangesAsync();

            await this.emailSender.SendEmailAsync(
                model.Email,
                model.Name,
                GlobalConstants.SystemEmail,
                model.Title,
                model.Content);

            return this.RedirectToAction("ThankYou");
        }

        public IActionResult ThankYou()
        {
            return this.View();
        }
    }
}

FoodForYou/Web/FoodForYou.Web/Controllers/OrderProductsController.cs
namespace FoodForYou.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using FoodForYou.Common;
    using FoodForYou.Data.Models;
    using FoodForYou.Services.Data.Interfaces;
    using FoodForYou.Services.Mapping;
    using FoodForYou.Web.ViewModels.OrderProducts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class OrderProductsController : BaseController
    {
        private readonly IOrderProductService orderProductsService;
        private readonly IProductService productsService;
        private readonly UserManager<ApplicationUser> userManager;

        public OrderProductsController(IOrderProductService orderProductsService, IProductService productsService, UserManager<ApplicationUser> userManager)
        {
            this.orderProductsService = orderProductsService;
            this.productsService = productsService;
            this.userManager = userManager;
        }

        public IActionResult AddToCart(int id)
        {
            this.ViewBag.ProductName = this.productsService.GetProductById(id).Name;
            this.ViewBag.ProductImageUrl = this.productsService.GetProductById(id).ImageUrl;
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int id, CreateOrderProductInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            var productPrice = this.productsService.GetPriceById(id);

            await this.orderProductsService.CreateOrderProductAsync(id, user.Id, productPrice, input.Quantity);
            return this.Redirect("/Categories/All");
        }

        public async Task<IActionResult> All()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var orderProducts = new AllProductsInCartViewModel
            {
                OrderedProducts = this.orderProductsService.GetAllByUserId<ProductInCartViewModel>(user.Id),
            };

            orderProducts.Sum = orderProducts.OrderedProducts.Sum(x => x.Price);
            return this.View(orderProducts);
        }

        public async Task<IActionResult> Clear()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var orderProducts = new ClearAllOrderedProductsInCart
            {
                OrderedProducts = this.orderProductsService.GetAllByUserId<ClearOrderedProductInCart>(user.Id),
            };

            await this.orderProductsService.ClearCartAsync(orderProducts.OrderedProducts);
            return this.Redirect("/Categories/All");
        }
    }
}

FoodForYou/Web/FoodForYou.Web/Controllers/OrdersController.cs
namespace FoodForYou.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using FoodForYou.Common;
    using FoodForYou.Data.Models;
    using FoodForYou.Data.Models.Enums;
    using FoodForYou.Services.Data.Interfaces;
    using FoodForYou.Web.ViewModels.OrderProducts;
    using FoodForYou.Web.ViewModels.Orders;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class OrdersController : BaseController
    {
        private const int ItemsPerPage = 5;

        private readonly IOrderService ordersService;
        private readonly IOrderProductService orderProductsService;
        private readonly UserManager<ApplicationUser> userManager;

        public OrdersController(IOrderService ordersService, IOrderProductService orderProductsService, UserManager<ApplicationUser> userManager)
        {
            this.ordersService = ordersService;
            this.orderProductsService = orderProductsService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> All(int page = 1)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var allOrders = new OrdersViewModel
            {
                AllOrders = this.ordersService.GetAllOrdersByUserId(user.Id, ItemsPerPage, (page - 1) * ItemsPerPage),
            };

            var count = this.ordersService.GetAllOrdersCountByUserId(user.Id);

            allOrders.PagesCount = (int)Math.Ceiling((double)count / ItemsPerPage);
            if (allOrders.PagesCount == 0)
            {
                allOrders.PagesCount = 1;
            }

            allOrders.CurrentPage = page;
            allOrders.OrdersCount = count;

            if (allOrders.CurrentPage > allOrders.PagesCount)
            {
                return this.BadRequest();
            }

            return this.View(allOrders);
        }

        public async Task<IActionResult> CompletedOrder()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            var latestOrder = this.ordersService.GetLatestOrder(user.Id);
            return this.View(latestOrder);
        }

        public async Task<IActionResult> ProceedToOrder()
        {
            var user = await this.userManager.GetUserAsync(this.User);

            if (this.orderProductsService.CurrentCountOrderProductsByUserId(user.Id) == 0)
            {
                return this.Redirect("/");
            }

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> ProceedToOrder(CreateOrderInputModel input)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.ordersService.CreateOrderAsync(user.Id, input.Address);
            return this.Redirect("/Orders/CompletedOrder");
        }
    }
}

FoodForYou/Web/FoodForYou.Web/Areas/Administration/Views/Shared/_Layout.cshtml
@using FoodForYou.Common
@using Microsoft.AspNetCore.Identity
@using FoodForYou.Data.Models
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacts" asp-action="Index">Contact us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="All">Menu</a>
                        </li>
                        @if (this.User.IsInRole(GlobalConstants.UserRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="OrderProducts" asp-action="All">Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="All">My Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FavouriteProducts" asp-action="All">Favourite Products</a>
                            </li>
                        }
                        else if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Administration" asp-controller="Orders" asp-action="LatestOrders">Latest Orders</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>